# Generated by Django 3.2.6 on 2021-08-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='Categoria',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='Descricao',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='videos',
            name='Titulo',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
